#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

// 音频配置
#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_4
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_2
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_3
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_1

#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_39
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_40
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

// 按钮配置
#define BOOT_BUTTON_GPIO        GPIO_NUM_0

// 显示屏配置
#define DISPLAY_SPI_SCK_PIN     GPIO_NUM_9
#define DISPLAY_SPI_MOSI_PIN    GPIO_NUM_10
#define DISPLAY_DC_PIN          GPIO_NUM_7
#define DISPLAY_SPI_CS_PIN      -1

#define DISPLAY_WIDTH   400
#define DISPLAY_HEIGHT  300
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY true

#endif // _BOARD_CONFIG_H_